//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conways_Game_of_Life.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conways_Game_of_Life.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aim Game ähnelt.
        /// </summary>
        internal static string Aim_Game_Text {
            get {
                return ResourceManager.GetString("Aim_Game_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] AimGame {
            get {
                object obj = ResourceManager.GetObject("AimGame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Around {
            get {
                object obj = ResourceManager.GetObject("Around", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Around ähnelt.
        /// </summary>
        internal static string Around_Text {
            get {
                return ResourceManager.GetString("Around_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big Glider Grenade ähnelt.
        /// </summary>
        internal static string Big_Glider_Grenade_Text {
            get {
                return ResourceManager.GetString("Big_Glider_Grenade_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Blackhole {
            get {
                object obj = ResourceManager.GetObject("Blackhole", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blackhole ähnelt.
        /// </summary>
        internal static string Blackhole_Text {
            get {
                return ResourceManager.GetString("Blackhole_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carpet ähnelt.
        /// </summary>
        internal static string Carpet_Text {
            get {
                return ResourceManager.GetString("Carpet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Conveyor_Belt {
            get {
                object obj = ResourceManager.GetObject("Conveyor_Belt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conveyor Belt ähnelt.
        /// </summary>
        internal static string Conveyor_Belt_Text {
            get {
                return ResourceManager.GetString("Conveyor_Belt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error!\nPlease make shure that you have enough room for your build\nPlease also make shure you dont have a currupted file ähnelt.
        /// </summary>
        internal static string Error_Text {
            get {
                return ResourceManager.GetString("Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Galaxy {
            get {
                object obj = ResourceManager.GetObject("Galaxy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Galaxy_Big {
            get {
                object obj = ResourceManager.GetObject("Galaxy_Big", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big_Galaxy ähnelt.
        /// </summary>
        internal static string Galaxy_Big_Text {
            get {
                return ResourceManager.GetString("Galaxy_Big_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Galaxy ähnelt.
        /// </summary>
        internal static string Galaxy_Text {
            get {
                return ResourceManager.GetString("Galaxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Game_of_life {
            get {
                object obj = ResourceManager.GetObject("Game_of_life", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game of Life ähnelt.
        /// </summary>
        internal static string Game_of_Life_Text {
            get {
                return ResourceManager.GetString("Game_of_Life_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Glider {
            get {
                object obj = ResourceManager.GetObject("Glider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Glider_Grenade {
            get {
                object obj = ResourceManager.GetObject("Glider_Grenade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glider Gun ähnelt.
        /// </summary>
        internal static string Glider_Gun_Text {
            get {
                return ResourceManager.GetString("Glider_Gun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glider ähnelt.
        /// </summary>
        internal static string Glider_Text {
            get {
                return ResourceManager.GetString("Glider_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] GliderGun {
            get {
                object obj = ResourceManager.GetObject("GliderGun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string Pause_Text {
            get {
                return ResourceManager.GetString("Pause_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Rocket {
            get {
                object obj = ResourceManager.GetObject("Rocket", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rocket ähnelt.
        /// </summary>
        internal static string Rocket_Text {
            get {
                return ResourceManager.GetString("Rocket_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Slugger {
            get {
                object obj = ResourceManager.GetObject("Slugger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slugger ähnelt.
        /// </summary>
        internal static string Slugger_Text {
            get {
                return ResourceManager.GetString("Slugger_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Small_Glider_Grenade {
            get {
                object obj = ResourceManager.GetObject("Small_Glider_Grenade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small Glider Grenade ähnelt.
        /// </summary>
        internal static string Small_Glider_Grenade_Text {
            get {
                return ResourceManager.GetString("Small_Glider_Grenade_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space Ship ähnelt.
        /// </summary>
        internal static string Space_Ship_Text {
            get {
                return ResourceManager.GetString("Space_Ship_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] SpaceShip {
            get {
                object obj = ResourceManager.GetObject("SpaceShip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Speed_Wall_Ladder {
            get {
                object obj = ResourceManager.GetObject("Speed_Wall_Ladder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed Wall Ladder ähnelt.
        /// </summary>
        internal static string Speed_Wall_Ladder_Text {
            get {
                return ResourceManager.GetString("Speed_Wall_Ladder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Spinner {
            get {
                object obj = ResourceManager.GetObject("Spinner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spinner ähnelt.
        /// </summary>
        internal static string Spinner_Text {
            get {
                return ResourceManager.GetString("Spinner_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start_Text {
            get {
                return ResourceManager.GetString("Start_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Teppich {
            get {
                object obj = ResourceManager.GetObject("Teppich", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Wallbuider {
            get {
                object obj = ResourceManager.GetObject("Wallbuider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wallbuilder ähnelt.
        /// </summary>
        internal static string Wallbuilder_Text {
            get {
                return ResourceManager.GetString("Wallbuilder_Text", resourceCulture);
            }
        }
    }
}
